export const currentStock = [
  {
    stock_id: 1,
    open_library_id: "OL27479W",
    title: "Amadeus: A Play...",
    author: "Peter Shaffer",
    publisher: "Example Publisher",
    publish_date: "1980",
    pages: 128,
    language: "en",
    isbn: "9780000000001",
    description: "Placeholder description. Later: fetch OpenLibrary work/edition description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    quantity: 3,
    condition: 4,
  },
  {
    stock_id: 2,
    open_library_id: "OL45033W",
    title: "Annotated Alice",
    author: "Lewis Carroll",
    publisher: "Example Publisher",
    publish_date: "2005",
    pages: 352,
    language: "en",
    isbn: "9780000000002",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/10521270-L.jpg",
    quantity: 1,
    condition: 4,
  },
  {
    stock_id: 3,
    open_library_id: "OL82563W",
    title: "Applied Numerical Analysis",
    author: "Curtis F. Gerald",
    publisher: "Example Publisher",
    publish_date: "2003",
    pages: 480,
    language: "en",
    isbn: "9780000000003",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/11153273-L.jpg",
    quantity: 2,
    condition: 3,
  },
  {
    stock_id: 4,
    open_library_id: "OL216365W",
    title: "Artaud Anthology",
    author: "Antonin Artaud",
    publisher: "Example Publisher",
    publish_date: "1995",
    pages: 220,
    language: "en",
    isbn: "9780000000004",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/10948956-L.jpg",
    quantity: 0,
    condition: 3,
  },
  {
    stock_id: 5,
    open_library_id: "OL9096W",
    title: "Asterios Polyp",
    author: "David Mazzucchelli",
    publisher: "Example Publisher",
    publish_date: "2010",
    pages: 344,
    language: "en",
    isbn: "9780000000005",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8235115-L.jpg",
    quantity: 1,
    condition: 5,
  },
  {
    stock_id: 6,
    open_library_id: "OL26274W",
    title: "Batman: Dark Victory",
    author: "Jeph Loeb",
    publisher: "Example Publisher",
    publish_date: "2001",
    pages: 312,
    language: "en",
    isbn: "9780000000006",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8235147-L.jpg",
    quantity: 3,
    condition: 4,
  },
  {
    stock_id: 7,
    open_library_id: "OL103332W",
    title: "Batman: Earth One",
    author: "Geoff Johns",
    publisher: "Example Publisher",
    publish_date: "2012",
    pages: 144,
    language: "en",
    isbn: "9780000000007",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8315041-L.jpg",
    quantity: 2,
    condition: 4,
  },
  {
    stock_id: 8,
    open_library_id: "OL23595W",
    title: "Batman: Haunted Knight",
    author: "Jeph Loeb",
    publisher: "Example Publisher",
    publish_date: "1996",
    pages: 192,
    language: "en",
    isbn: "9780000000008",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8235069-L.jpg",
    quantity: 2,
    condition: 3,
  },
  {
    stock_id: 9,
    open_library_id: "OL5921W",
    title: "Batman: The Black Mirror",
    author: "Scott Snyder",
    publisher: "Example Publisher",
    publish_date: "2011",
    pages: 304,
    language: "en",
    isbn: "9780000000009",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8235108-L.jpg",
    quantity: 1,
    condition: 4,
  },
  {
    stock_id: 10,
    open_library_id: "OL24340W",
    title: "Batman: The Dark Knight Returns",
    author: "Frank Miller",
    publisher: "Example Publisher",
    publish_date: "1986",
    pages: 224,
    language: "en",
    isbn: "9780000000010",
    description: "Placeholder description.",
    subjects: [],
    cover_url: "https://covers.openlibrary.org/b/id/8235133-L.jpg",
    quantity: 1,
    condition: 3,
  },
];
